DROP DATABASE IF EXISTS demo;
CREATE DATABASE demo;

DROP TABLE IF EXISTS demo.Activity;
CREATE TABLE demo.Activity
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255)
);

DROP TABLE IF EXISTS demo.Admin;
CREATE TABLE demo.Admin
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Username VARCHAR(255),
  Password VARCHAR(255)
);

DROP TABLE IF EXISTS demo.Enroll;
CREATE TABLE demo.Enroll
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Sno VARCHAR(255),
  Sname VARCHAR(255),
  ActivityId INT
);

ALTER TABLE demo.Enroll ADD FOREIGN KEY (ActivityId) REFERENCES Activity (Id);
CREATE INDEX FK_Enroll ON demo.Enroll (ActivityId);
